version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./web/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PROJECT_ROOT=/app/../../../..
    volumes:
      - .:/app/../../../..
      - /tmp
    depends_on:
      - redis
    networks:
      - ai-reasoning-lab

  # Frontend
  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://backend:8000
    depends_on:
      - backend
    networks:
      - ai-reasoning-lab

  # Redis for sessions and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-reasoning-lab

  # Ollama for local LLM inference (optional)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ai-reasoning-lab
    profiles:
      - with-ollama

volumes:
  redis_data:
  ollama_data:

networks:
  ai-reasoning-lab:
    driver: bridge